names: 通用模板
standards:
  # [0names,1classify,2acorn,3methods,4cycle,5memo,6s_no,7types]
  - [任务执行延期, 10, -10, 2, -1, '', '',0]
  - [任务执行, 4, 10, 2, -1, '', '',1]
  - [加班, 10, 5, 2, -1, '', '',0]
  - [办公桌面不整洁, 3, -2, 2, -1, '', '',0]
  - [早退, 10, -5, 2, -1, '', '',0]
  - [迟到, 10, -5, 2, -1, '', '',0]
  - [最后一个离开公司, 10, 2, 2, -1, '', '',0]
  - [第一个到公司, 10, 2, 2, -1, '', '',0]
  - [办公区域抽烟, 10, -10, 2, -1, '', '',0]
  - [周报, 8, 10, 2, -1, '', '',0]
  - [培训, 9, 10, 2, -1, '', '',0]