names: 通用模板
standards:
  # [0names,1classify,2acorn,3methods,4cycle,5memo,6s_no,7types]
  - [原创性行业文章, 5, 20, 2, -1, '', '',0]
  - [原创性技术文档, 5, 20, 2, -1, '', '',0]
  - [主动学习提高专业水平, 6, 5, 2, -1, '', '',0]
  - [相关职位未能完成每月加减分任务, 4, -10, 2, 2, '', '',0]
  - [参加客户会议, 4, 5, 2, -1, '', '']
  - [周报汇报详细，有计划性, 4, 5, 2, -1, '', '',0]
  - [及时处理系统BUG, 4, 5, 2, -1, '', '',0]
  - [采购办公用品, 4, 5, 2, -1, '', '',0]
  - [负责合作企业外联汇报事项, 4, 5, 2, -1, '', '',0]
  - [数据库误操作, 4, -50, 2, -1, '', '',0]
  - [服务器出现一次严重故障（影响超过30分钟）, 4, -50, 2, -1, '', '',0]
  - [服务器出现一次普通故障（影响30分钟之内）, 4, -10, 2, -1, '', '',0]
  - [每个数据库维护, 4, 10, 2, 2, '', '',0]
  - [安装一个新服务器, 4, 20, 2, -1, '', '',0]
  - [每台服务器维护, 4, 10, 2, 2, '', '',0]
  - [尾款, 4, 20, 2, -1, '', '',0]
  - [客服对接商机, 4, 5, 2, -1, '', '',0]
  - [创造商机, 4, 20, 2, -1, '', '',0]
  - [统计影响力, 4, 30, 2, 2, '', '',0]
  - [交社保、公积金, 4, 5, 2, -1, '', '',0]
  - [签单, 4, 30, 2, -1, '', '',0]
  - [做方案, 4, 5, 2, -1, '', '',0]
  - [约谈客户, 4, 5, 2, -1, '', '',0]
  - [开发票, 4, 5, 2, -1, '', '',0]
  - [公司网站文章发布, 4, 10, 2, -1, '', '',0]
  - [公司公众号文章群发, 4, 10, 2, -1, '', '',0]
  - [申请公众号（注册、认证、微信支付）, 4, 10, 2, -1, '', '',0]
  - [申请公众号（注册、认证）, 4, 8, 2, -1, '', '',0]
  - [升级, 4, 5, 2, -1, '', '',0]
  - [任务执行延期, 4, -10, 2, -1, '', '',0]
  - [任务执行, 4, 10, 2, -1, '', '',1]
  - [引导客户，减少开发工作量, 2, 5, 2, -1, '', '',0]
  - [小组长, 2, 20, 2, 2, '', '',0]
  - [经理, 2, 30, 2, 2, '', '',0]
  - [总监, 2, 50, 2, 2, '', '',0]
  - [专科, 2, 30, 2, 2, '', '',0]
  - [本科, 2, 50, 2, 2, '', '',0]
  - [帮助同事解决工作上的难点问题, 2, 5, 2, -1, '', '',0]
  - [组织培训, 2, 15, 2, -1, '', '',0]
  - [承诺的事情没做到, 3, -8, 2, -1, '', '',0]
  - [主动积极帮助同事处理生活中难题, 3, 2, 2, -1, '', '',0]
  - [加班, 3, 5, 2, -1, '', '',0]
  - [办公桌面不整洁, 3, -2, 2, -1, '', '',0]
  - [上班后吃早餐, 3, -2, 2, -1, '', '',0]
  - [被客户投诉, 3, -5, 2, -1, '', '',0]
  - [跟客户沟通获得客户好感及肯定, 3, 5, 2, -1, '', '',0]
  - [外出消费开公司发票（消费金额200以上）, 3, 1, 2, -1, '', '',0]
  - [说公司不好, 3, -10, 2, -1, '', '',0]
  - [讨论和传递负面情绪, 3, -10, 2, -1, '', '',0]
  - [主动正面宣传公司产品或者文化（如朋友圈）, 3, 2, 2, -1, '', '',0]
  - [积极主动处理问题, 3, 2, 2, -1, '', '',0]
  - [勇于主动承担责任, 3, 2, 2, -1, '', '',0]
  - [合理的工作计划, 3, 2, 2, -1, '', '',0]
  - [提出合理化建设意见, 3, 2, 2, -1, '', '',0]
  - [重要场合着装非常得体, 3, 2, 2, -1, '', '',0]
  - [保护公司财产, 3, 5, 2, -1, '', '',0]
  - [给同事带好吃的, 3, 5, 2, -1, '', '',0]
  - [请同事吃饭, 3, 5, 2, -1, '', '',0]
  - [早退, 3, -5, 2, -1, '', '',0]
  - [迟到, 3, -5, 2, -1, '', '',0]
  - [最后一个离开公司, 3, 2, 2, -1, '', '',0]
  - [第一个到公司, 3, 2, 2, -1, '', '',0]
  - [有素质讲礼貌的习惯, 3, 5, 2, -1, '', '',0]
  - [未能检查电器水源是否关闭, 1, -2, 2, -1, '', '',0]
  - [请假（事假）, 1, -5, 2, -1, '', '',0]
  - [爱心捐助, 1, 8, 2, -1, '', '',0]
  - [拾金不昧, 1, 2, 2, -1, '', '',0]
  - [见义勇为, 1, 15, 2, -1, '', '',0]
  - [献血, 1, 20, 2, -1, '', '',0]
  - [主动养护公司绿植, 1, 2, 2, -1, '', '',0]
  - [主动清理垃圾, 1, 2, 2, -1, '', '',0]
  - [主动整理公司环境, 1, 2, 2, -1, SH0001, '',0]