Admin\Entity\ProductSprice:
  type: entity
  table: product_sprice
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ''
      id: true
      generator:
        strategy: IDENTITY
  fields:
    productId:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
      column: product_id
    skuId:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
      column: sku_id
    levels:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    price:
      type: decimal
      nullable: true
      precision: 10
      scale: 2
      comment: ''
    marketPrice:
      type: decimal
      nullable: true
      precision: 10
      scale: 2
      comment: ''
      column: market_price
    status:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
    sid:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
  lifecycleCallbacks: {  }
