Admin\Entity\ProductCategory:
  type: entity
  table: product_category
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ''
      id: true
      generator:
        strategy: IDENTITY
  fields:
    parentid:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
    names:
      type: string
      nullable: true
      length: 50
      fixed: false
      comment: ''
    sort:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    thumb:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
    status:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
  lifecycleCallbacks: {  }
