Admin\Entity\Settings:
  type: entity
  table: settings
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ''
      id: true
      generator:
        strategy: IDENTITY
  fields:
    sid:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
    names:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
    settings:
      type: string
      nullable: true
      length: 2048
      fixed: false
      comment: ''
    status:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
  lifecycleCallbacks: {  }
