Admin\Entity\WelfareSettings:
  type: entity
  table: welfare_settings
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ''
      id: true
      generator:
        strategy: IDENTITY
  fields:
    sid:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
    materials:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    lucky:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    luckyPrize:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
      column: lucky_prize
    bonus:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    bonusPool:
      type: decimal
      nullable: true
      precision: 20
      scale: 2
      comment: ''
      column: bonus_pool
    snack:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    snackUserId:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
      column: snack_user_id
    snackNum:
      type: integer
      nullable: true
      unsigned: false
      comment: ''
      column: snack_num
    name:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
    types:
      type: smallint
      nullable: true
      unsigned: false
      comment: ''
    memo:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
    sysmemo:
      type: string
      nullable: true
      length: 255
      fixed: false
      comment: ''
  lifecycleCallbacks: {  }
